### ISSUE TITLE
Matrix is not positive definite

### ISSUE THREAD

**Issue by andreydung** [all-umass/metric-learn#65]
I'm using the Covariance object on my own dataset. Here is the [data](http://cronus.eecs.northwestern.edu/html/data.csv).

```
(5245, 258)
Traceback (most recent call last):
  File "train_metric.py", line 61, in <module>
    X_trained = ml.transform(X)
  File "/home/andrey/anaconda2/lib/python2.7/site-packages/metric_learn/base_metric.py", line 46, in transform
    L = self.transformer()
  File "/home/andrey/anaconda2/lib/python2.7/site-packages/metric_learn/base_metric.py", line 29, in transformer
    return inv(cholesky(self.metric()))
  File "/home/andrey/anaconda2/lib/python2.7/site-packages/numpy/linalg/linalg.py", line 612, in cholesky
    r = gufunc(a, signature=signature, extobj=extobj)
  File "/home/andrey/anaconda2/lib/python2.7/site-packages/numpy/linalg/linalg.py", line 93, in _raise_linalgerror_nonposdef
    raise LinAlgError("Matrix is not positive definite")
numpy.linalg.linalg.LinAlgError: Matrix is not positive definite
```

Will it be better if the code use pinv instead of inv?

**Comment by perimosocordiae** [comment]
The issue here is that your data does not cover all 258 dimensions, which results in a rank-deficient covariance matrix. If you preprocess your data with PCA and take the principal components explaining 99% of the variance, you only need 5 dimensions:

```python
import numpy as np
from sklearn.decomposition import PCA

x = np.loadtxt('data.csv', delimiter=',')  # shape = (5245, 258)
px = PCA(n_components=0.99).fit_transform(x)  # shape = (5245, 5)
```

Now the covariance of `px` is full-rank (5) and everything should work as intended.

I think it's outside the scope of the `Covariance` method to do this sort of preprocessing, but it might be useful to have an example like this in the docs somewhere.

**Comment by andreydung** [comment]
Thanks! So I should always apply PCA before using any metric learning algorithms implemented here?

**Comment by perimosocordiae** [comment]
Most of the algorithms here either handle this case natively or give an option to apply PCA before learning (see https://github.com/all-umass/metric-learn/blob/master/metric_learn/rca.py#L64), so it varies case-by-case.

I would say that it's unlikely to hurt, though, especially with your particular dataset.
